### PR TITLE
Updated README and added requirements.txt

### PR DESCRIPTION
**Pull request by bigsnarfdude**

### CODE REVIEW

**Comment by bigsnarfdude** [comment]
just added download_data.py as well

**Comment by MarvinTeichmann** [comment]
Thanks. 433fad3 and f7babff look good.

 2152981 on the other hand will not work like this. The script will not be able to find the files  `["train_2.idl", "train_3.idl", "train_4.idl", "val_2.idl", "val_3.idl", "val_4.idl"] ` to copy them into the data_dir. In addition the script does not download and handle the segmentation data. 

Can you remove 2152981 from your master? Then I can merge this pull request and handle the download_data later.

**Comment by bigsnarfdude** [comment]
download_data.py removed by hard reset to 433fad3f7c60bca253c83dc672121e80b35d7108

**Comment by MarvinTeichmann** [comment]
Thanks!

**Pull request merged**
