### PR TITLE
run demo ok

### PR DESCRIPTION
**Pull request by zdx3578**
add some code for run demo; prepare some download or dir ;

### CODE REVIEW

**Comment by zdx3578** [comment]
maybe ubuntu 16 is ok；this code for ubuntu 14;

**Comment by MarvinTeichmann** [comment]
Thanks for the pull request. I have seen that there are lot's of issues and I am looking into it. I was rather busy with the ICCV deadline recently. So I couldn't respond earlier.

**Comment by MarvinTeichmann** [comment]
Thanks for the pull request. The underline issue was however, that the base_path was not set correctly. I fixed that in 5ba41b09. I prefer that fix, as it sets all pathes correctly.

Did you pull request fix any other issues then:
1) creating 'run_dir"
2) Setting the include pathes?

If not I would close this.

Marvin

**Comment by MarvinTeichmann** [comment]
Closed for now, as the main issues have been fixed in different commits.

**Pull request closed without merging**
